# Generated by Django 5.0.4 on 2024-05-03 07:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comment_comment_alter_comment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_listing', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 7, 20, 51, 404501)),
        ),
    ]
