# Generated by Django 5.0.4 on 2024-05-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listing_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
    ]
