# Generated by Django 5.0.4 on 2024-05-03 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_listing_current_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_highest_bid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_bid', to='auctions.bid'),
        ),
    ]
