# Generated by Django 5.0.4 on 2024-05-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='highest_bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='initial_price',
            field=models.FloatField(default=None),
        ),
    ]
